export const bankNames = [
  { name: 'BCA' },
  { name: 'BRI' },
  { name: 'BNI' },
  { name: 'Mandiri' },
  { name: 'BTN' },

  { name: 'CIMB Niaga' },
  { name: 'Danamon' },
  { name: 'Permata Bank' },
  { name: 'Panin Bank' },
  { name: 'Maybank' },
  { name: 'OCBC NISP' },
  { name: 'Bank Mega' },
  { name: 'HSBC Indonesia' },
  { name: 'Citibank' },
  { name: 'UOB Indonesia' },
  { name: 'Bank Sinarmas' },
  { name: 'Bank Jago' },
  { name: 'Bank BTPN' },
  { name: 'Bank BTPN Syariah' },
  { name: 'Bank Muamalat' },
  { name: 'Bank Syariah Indonesia (BSI)' },

  { name: 'SeaBank' },
  { name: 'Jenius (BTPN)' },
  { name: 'Blu (BCA Digital)' },
  { name: 'Neo Commerce (BNC)' },
  { name: 'Line Bank' },
  { name: 'Allo Bank' },
  { name: 'Bank Raya' },
];
