export const Categories = [
  { value: 'fashion', label: 'Fashion & Apparel' },
  { value: 'electronics', label: 'Electronics & Gadgets' },
  { value: 'food_beverage', label: 'Food & Beverage' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'home_living', label: 'Home & Living' },
  { value: 'sports', label: 'Sports & Outdoor' },
  { value: 'automotive', label: 'Automotive & Accessories' },
  { value: 'books', label: 'Books & Stationery' },
  { value: 'toys', label: 'Toys & Kids' },
  { value: 'baby', label: 'Baby & Maternity' },
  { value: 'pets', label: 'Pet Supplies' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'office', label: 'Office & Workspace' },
  { value: 'digital_products', label: 'Digital Products' },
  { value: 'services', label: 'Services' },
  { value: 'handmade', label: 'Handmade & Crafts' },
  { value: 'groceries', label: 'Groceries' },
  { value: 'music', label: 'Music & Instruments' },
  { value: 'photography', label: 'Photography & Video' },
];
